### ISSUE TITLE
MSqRob installation

### ISSUE THREAD

**Issue by david-bouyssie** [statOmics/MSqRob#1] opened 2017-01-31 10:19 UTC
We had some issues to install MSqRob on a windows comuter.
Here is the procedure we used to make it work.
It may help somebody else.

```R
install.packages("devtools")
library(devtools)

source("https://bioconductor.org/biocLite.R")
biocLite("Biobase")
biocLite("limma")
biocLite("MSnbase")
biocLite("preprocessCore")
biocLite("vsn")

install.packages("lme4")
install.packages("htmltools")
install.packages("httpuv")
install.packages("xtable")
install.packages("DT")
install.packages("shinyjs")

devtools::install_github("ludgergoeminne/MSqRob")
library(MSqRob)

shiny::runApp(system.file("App-MSqRob", package="MSqRob"))
```

Here are our session data:
```R
session info:

Session info ----------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (0.99.903)          
 language (EN)                        
 collate  French_France.1252          
 tz       Europe/Paris                
 date     2017-01-20                  

Packages --------------------------------------------------------------------------------------------------------------------------
 package  * version date       source                                
 devtools * 1.12.0  2016-06-24 CRAN (R 3.3.2)                        
 digest     0.6.11  2017-01-03 CRAN (R 3.3.2)                        
 lattice    0.20-34 2016-09-06 CRAN (R 3.3.2)                        
 lme4     * 1.1-12  2016-04-16 CRAN (R 3.3.2)                        
 MASS       7.3-45  2016-04-21 CRAN (R 3.3.1)                        
 Matrix   * 1.2-7.1 2016-09-01 CRAN (R 3.3.2)                        
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.2)                        
 minqa      1.2.4   2014-10-09 CRAN (R 3.3.2)                        
 MSqRob   * 0.6.2   2017-01-17 Github (ludgergoeminne/MSqRob@47285d0)
 nlme       3.1-128 2016-05-10 CRAN (R 3.3.1)                        
 nloptr     1.0.4   2014-08-04 CRAN (R 3.3.2)                        
 Rcpp       0.12.9  2017-01-14 CRAN (R 3.3.2)                        
 withr      1.0.2   2016-06-20 CRAN (R 3.3.2)                      

Warning: Error in renderPlot: Please provide a protein groups file or untick the box "Remove proteins that are only identified by modified peptides".

Warning: Error in check_expAnn: Make sure that exactly one column in the experiment annotation has elements equal to the mass spec run names in the data. Maybe one of the following columns has an error in at least one of its elements: run.
```

**Comment by ludgergoeminne** [comment] 2017-03-15 11:10
I have added a `biocViews:` line to the DESCRIPTION file.
According to this thread, that should fix the problem:
https://github.com/hadley/devtools/issues/700

**Comment by ludgergoeminne** [comment] 2017-04-06 16:52
Apparently the issue is with `install_github` (https://github.com/hadley/devtools/issues/1298) not being able to install dependencies of dependencies. I have now added all dependencies of my dependencies in my DESCRIPTION file as a temporary solution. If anyone still have issues in installing MSqRob, please let me know! I will close this issue for now.

**Closed as completed** 2017-04-06 16:53 UTC

**Comment by magnusarntzen** [comment] 2017-12-05 08:03
Hi!
My apologies for reopening this thread, but I was not able to install MSqRob following the protocol on the main page here at GitHub.

All goes fine untill the very end:

```
> shiny::runApp(system.file("App-MSqRob", package="MSqRob"))
Error in shinyAppDir(x) : No Shiny application exists at the path ""
```
Looking in HOME/Documents/R/win-library/3.4/, I can find the MSqRob package, but no App.
Any ides on how to resolve this?

Thanks, and best regards,
Magnus Arntzen

**Comment by ludgergoeminne** [comment] 2017-12-08 18:11
Dear Magnus

This is an error I haven't encountered yet. It seems very strange that you can install MSqRob, but not the app.

I would first try to remove MSqRob completely and then try to reinstall it,
making sure you have all the administrator rights on your computer.
If you still get the same error after that, can you tell me what the output of this line of code is?

system.file("App-MSqRob", package="MSqRob")

Also, can you check if there is a subfolder called "App-MSqRob" in the MSqRob folder in your windows library? If there is not, what you can try to do, is make such a subfolder yourself and copy all the content of the "inst/App-MSqRob" folder here on GitHub into it. However, keep this as a last rescue, because normally, the app should be smoothly installed when you follow the installation instructions. 

Please let me know how and if any of these things work.

Cheers

Ludger

**Comment by magnusarntzen** [comment] 2017-12-11 09:10
Dear Ludger

Thank you very much for your suggestions. There was no subfolder named "App-MSqRob" in the MSqRob folder in the windows-library.

However, I think this error might be an artefact of Folder Redirection on Win10. My win-library folder is in Documents, and Documents is within Win10 redirected to Z:\ (Home area). That is where I found MSqRob. However, after a bit of searching, I found the "App-MSqRob" on C: where the installation scripts had made a new win-library under a new root folder. Strange behavior!

Anyways, moving this folder to the true win-library on Z, everything works smoothly.

Thanks again for your help!

Cheers,
Magnus

**Comment by ludgergoeminne** [comment] 2017-12-11 11:15
Strange behavior indeed, I'll keep it in mind if other people would face similar problems.

You're most welcome!

**Comment by yuanpeibo** [comment] 2019-01-05 05:11
Hello, I am coming to look for some help here for unable to install MSqRob following the protocol on the main page here at GitHub.
"devtools" and "BiocManager" were successfully  installed, the problem is that I can not open URL in the following step. Because my location is in China, so I tried every  cran mirrors in China, but it didn't work.
The specific error are showing below:
> devtools::install_github("statOmics/MSqRob@MSqRob0.7.6")
Downloading GitHub repo statOmics/MSqRob@MSqRob0.7.6
Error in utils::download.file(url, path, method = download_method(), quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/statOmics/MSqRob/tarball/MSqRob0.7.6'

**Comment by ludgergoeminne** [comment] 2019-01-05 11:27
Dear Yuan

Installing MSqRob still seems to work on my side.
Maybe it is not an MSqRob-related problem.
Could you for example try to install a package from another repository?
E.g.:
devtools::install_github("lgatto/mzR")
and see if that works?

If that also doesn't work, it might be related to the "install_github" function.
Maybe you could then open an issue there?

Best regards

Ludger

**Comment by yuanpeibo** [comment] 2019-01-05 12:51
Dear Ludger

Thank you for your reply. I've tried to install another package as you suggested and it failed again.
So, it's probably an "install_github" related problem.
I will try to find help there.

Thanks again
Best wishes

Yuan

**Comment by ludgergoeminne** [comment] 2019-01-05 14:49
Dear Yuan

You're welcome and good luck in finding a solution!
If you know what the issue is, feel free to post the solution over here as well,
it might help others with a similar problem.

Best wishes

Ludger

**Comment by mchiapello** [comment] 2020-11-27 22:18
Hi @ludgergoeminne ,
trying to install MSqRob I received the following output: 

```
* installing *source* package ‘MSqRob’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package ‘lme4’ was built under R version 4.0.2
Execution halted
ERROR: lazy loading failed for package ‘MSqRob’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/MSqRob’
Error: Failed to install 'MSqRob' from GitHub:
  (converted from warning) installation of package ‘/var/folders/9s/jk05tyb12gb5qbs7gg28k63m0000gp/T//Rtmpd8esJg/file3d0c410af653/MSqRob_0.7.7.tar.gz’ had non-zero exit status
```

Any advice?

Thank you,
M

**Comment by Radiosynthesis** [comment] 2021-03-02 18:42
Hi,

I am having problems with the devtools and I was wondering if you can help me with it. I installed devtools with install.packages("devtools") and then I proceed with library(devtools) and I keep getting this error and I am unsure how to solve this with my Mac (Big Sur):

> install.packages("devtools")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/devtools_2.3.2.tgz'
Content type 'application/x-gzip' length 337605 bytes (329 KB)
==================================================
downloaded 329 KB


The downloaded binary packages are in
	/var/folders/jg/sxmylxqs50jc7gtncrl261dh0000gn/T//RtmpniQg2Q/downloaded_packages
> library(devtools)
Loading required package: usethis
Error: package or namespace load failed for ‘devtools’:
 .onLoad failed in loadNamespace() for 'processx', details:
  call: loadNamespace(name)
  error: there is no package called ‘ps’

**Comment by Radiosynthesis** [comment] 2021-03-02 18:58
I also tried this with my Mac (Big Sur) and received an error message.

> devtools::install_github("hadley/devtools")
Error: .onLoad failed in loadNamespace() for 'processx', details:
  call: loadNamespace(name)
  error: there is no package called ‘ps’
